### ISSUE TITLE
Create DriveTrain

### ISSUE THREAD

**Issue by Qiucj** [The-Charge/Recharge2020#1]
Create the DriveTrain Subsystem.

**Comment by AshwinS27** [comment]
Also, coordinate with Mechanical/Electrical regarding the number of motor controllers.

**Comment by Shalmezad** [comment]
If the drive train's our classic 6-wheel+ style, you can go ahead and set it up in robot builder with just 2 motors/controllers (left/right), and leave a `TODO` comment (https://dev.to/eclecticcoding/todo-list-in-vscode-2mnb)
So long as you don't access the motors outside the sub-system (make sure they're private in the subsystem, have commands call/use a `drive()` method), it's trivial to add more controllers at a later date if the number is wrong.
