### ISSUE TITLE
Cooling system

### ISSUE THREAD

**Issue by AshwinS27** [The-Charge/Recharge2020#26]
Add a subsystem with a single solenoid which is always on

**Comment by abcurrie** [comment]
Ashwin, should this really be closed.  I thought there was some mention of
having the ability to turn on and off the solenoid base upon temperature
readings from the Falcons.  Is this in place?

**Comment by AshwinS27** [comment]
Since we don't want the compressor to run the entire match we are going to have a command which is going to check if the TalonFX ever exceeds a certain temperature. The solenoid should kick in then. Once it gets below a certain temperature (a range below the temperature which kicks the cooling in), the solenoid should be switched off.
