### ISSUE TITLE
Robot Simulation

### ISSUE THREAD

**Issue by Shalmezad** [The-Charge/Recharge2020#4]
It appears WPILib added a simulation suite to this year's extensions.
Documentation can be found here:
https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/robot-simulation/index.html

**Comment by JanSpgh** [comment]
Test the robot simulator with resistance 2019 code(just learn to use the tool).

**Comment by JanSpgh** [comment]
Robot Simulation do not have any use for us. It does not support the Talon SRX

**Comment by Shalmezad** [comment]
Reopening. Would like more info on the "it does not support the Talon SRX", as when I tested it, the talons are showing up (although, under "other devices"):
https://imgur.com/a/qgyLIJO

Please post what errors you're getting/receiving if any, or if what I'm seeing is a red herring.

**Comment by Shalmezad** [comment]
Also, please branch and push your version of the 2019 code updated for the 2020 extension. There's a number of changes that have to be done to make it compatible with the 2020 extensions which may be why the talons don't appear to work.

**Comment by AshwinS27** [comment]
Robot Simulation works with Talons now. We have used it to test ToggleLockStraight.
