### ISSUE TITLE
Subsystem periodic() & REV ColorSensor

### ISSUE THREAD

**Issue by Shalmezad** [The-Charge/Recharge2020#6]
Subsystems now have a `periodic()` method called once every scheduler run. 
Normally, we run stuff in command `execute()` methods, but there are use cases for this periodic() method. The main 2 being:

- Our debug stuff (`writeDebugToDashboard`, `readValuesFromDashboard`)
- Constant running things

For the latter, sensors would make a great use case.
Though it's not one of our game priorities, should look into the REV color sensor, and add it to a test control panel subsystem.

What I would recommend a student to look into if time permits or it's needed:

1. Read the [specs](http://www.revrobotics.com/rev-31-1557/) on what the color sensor has available to it. 
2. Review the [example code](https://github.com/REVrobotics/Color-Sensor-v3-Examples/blob/master/Java/Read%20RGB%20Values/src/main/java/frc/robot/Robot.java#L71)
3. Make a control panel subsystem, add a rev color sensor (note that robot builder may not have this built in, and you have to add it in manually)
4. Add a couple variables:
    - Last color seen (may want to make a java enum)
    - Can see control panel (boolean)
    - Last known control panel direction (also probably an enum)
    - Known rotations (float)
5. In the subsystem's `periodic`:
    - See if the sensor can see the control panel (use proximity sensor)
    - If so, grab the current color value, compare it to last color value
    - If it changed:
        - See what direction the wheel is (this is based on what color it was vs. what it is now)
        - Update the # of known rotations (I think it's 1/8 rotation per color change, check the field)
    - Throw the above variables on the dashboard

**Comment by AshwinS27** [comment]
Finished Control Panel code, tested on Plybot and merged.
