### ISSUE TITLE
Button Box Programming

### ISSUE THREAD

**Issue by AshwinS27** [The-Charge/Recharge2020#8]
Research ButtonBox and Pokey Board interface.
We should be able to take input for both analog and digital buttons and easily map them to commands.

**Comment by neuenfeldttj** [comment]
I downloaded PoKeys software, but need to find PoBlocks and how it connects to Java/robot.

**Comment by Shalmezad** [comment]
The way we've traditionally used the PoKey board, we have it simulate a USB joystick on the PoKey side. This means in the driverstation side, it's treated as just a regular old joystick ( see [previous year's code](https://github.com/The-Charge/Resistance2019/blob/master/src/main/java/org/usfirst/frc2619/Resistance2019/OI.java#L136) ), and thus can rig up `Joystick` and `JoystickButton` in robot builder just like you would a plain old joystick.

For the PoKey side, you'll need to figure out how to rig up digital/analog inputs to simulated joystick buttons & axis'. Most of what you need can be found in the "Joystick mapping" section (page 42) of the [PoKeys user manual](https://www.poscope.com/wp-content/uploads/downloads/Pokeys/Manuals/PoKeys%20user%20manual%20(19.8.2017).pdf)

**Comment by abcurrie** [comment]
I'll admit that the documentation on the Pokey board is overwhelming.
Fortunately most of the stuff we don't use.

We only use the configuration on the Pokey board to emulate a joystick as
Richard says.  Mostly we need to map the buttons to the right inputs and
sometimes switch the logic state of the input to account for wiring
differences.

Button boxes are something that can be worked on outside of the build site
if someone wanted to take it home and work on it.

**Comment by neuenfeldttj** [comment]
I know how to program digital buttons/analog inputs and use them in Robot code.
