### ISSUE TITLE
Shuffleboard

### ISSUE THREAD

**Issue by AshwinS27** [The-Charge/Recharge2020#9]
We have never used Shuffleboard before. I would like one person to research in-depth into it so we can use it for debugging.
You can find helpful resources on WPILib Docs and Chief Delphi

**Comment by rheeil** [comment]
I read shuffleboard guide thing and figured out how to launch it from visual studios. I had an error trying to use it though, when I wrote the command it said  SmartDashboard.putNumber("Literally a random number", 10); it said "Smart Dashboard cannot be resolved". Not really sure what that means but I'm going to keep researching.

**Comment by Shalmezad** [comment]
>  when I wrote the command it said SmartDashboard.putNumber("Literally a random number", 10); it said "Smart Dashboard cannot be resolved".

I don't see your branch in github so while I cannot diagnose the issue exactly my current guess is you're missing the smart dashboard import at the top of whatever file you put it in:
`import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;`

For anything involving "<Foo> cannot be resolved" (under problems), or "error: cannot find symbol" (when trying to build), you can usually try the "quick fix" option (mouse over the keyword in red, quick fix is in the bottom of the tooltip popup) and see if there's an "Import <packagename>" that will fix the issue.

Also, @AshwinS27, please remind the programming team that it's good practice at the end of the day to commit & push what they have (hopefully they also know to branch off first....). In doing so, I can help diagnose issues during my lunch break.

**Comment by abcurrie** [comment]
All,

Ashwin raises a very good issue of everyone using Github properly.  All
projects that people are working on should be in a project folder in
Github.  This is the only way for other people to help review the code and
to help troubleshoot when away from the build site.

Thanks to Isabella for updating the issue with status.  We need to know the
current status of the project and it allows us to offer help.

Hopefully you found this link to get info on shuffleboard:
https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/shuffleboard/index.html
